databases:
  - name: backendjob
    databaseName: backendjob
    user: backendjob_user

services:
  - type: web
    name: GetThatJob_BackEnd
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backendjob
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
